shared:
  features:
    registration: <%= ENV.fetch("REGISTRATON_FEATURE", true) %>
    voice: <%= ENV.fetch("VOICE_FEATURE", false) %>
  settings:
    google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] || Rails.application.credentials[:google_client_id] %>
    google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] || Rails.application.credentials[:google_client_secret] %>
    whatsapp_key: <%= ENV["WHATSAPP_KEY"] || Rails.application.credentials[:whatsapp_key] %>
